### ISSUE TITLE
missing epilepsy warning :-)

### ISSUE THREAD

**Issue by tobozo** [armel/DRADIS#1]
[blink/flash effect](https://twitter.com/gsreynaga/status/1692965179498070366) removed with a few modifications, rendering is a bit slower though.

let me know if you want a PR for this 😊 

https://github.com/armel/DRADIS/assets/1893754/26bde9b6-ab8a-4460-8676-0e41591e24ea

**Comment by armel** [comment]
Hi :) 

I was sure you would find a way to solve this problem :) I'm interested by your PR of course :) Thank you.

Armel.
